version: "3.8"

services:
  n8n:
    image: n8nio/n8n:latest
    environment:
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
    volumes:
      - ./.n8n:/home/node/.n8n
    ports:
      - "5678:5678"
    restart: unless-stopped
